# Stage 1: Setup environment
FROM node:22.11.0 AS builder

WORKDIR /usr/src/app

COPY . .
# RUN npm install -g npm@11.0.0
RUN npm cache clean --force
RUN npm install

# Add fix for nuxt/builder.js to accept ignoreOptions
RUN sed -i '/ignoreArray: this.options.ignore/s/$/,/; /ignoreArray: this.options.ignore/a \      ignoreOptions: this.options.ignoreOptions' node_modules/@nuxt/builder/dist/builder.js

CMD ["npm", "run", "dev"]
